AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Meowlin serverless demo application

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: nodejs22.x

Resources:
  MeowlinHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: "$default"
      DefaultRouteSettings:
        ThrottlingBurstLimit: 5
        ThrottlingRateLimit: 2

  RequestUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meowlin-request-upload-url
      CodeUri: src/request-upload-url/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MeowlinClipsTable
      Events:
        RequestUploadUrl:
          Type: HttpApi
          Properties:
            ApiId: !Ref MeowlinHttpApi
            Path: /uploads
            Method: POST

  MeowlinClipsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MeowlinClips
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: clipId
          AttributeType: S
      KeySchema:
        - AttributeName: clipId
          KeyType: HASH

Outputs:
  MeowlinApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${MeowlinHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
